"""setup

Revision ID: 3268b0b6a51b
Revises: 
Create Date: 2021-07-21 12:15:13.345420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3268b0b6a51b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('blog_title', sa.String(length=64), nullable=False),
    sa.Column('blog_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_blog_title'), ['blog_title'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_image', sa.String(length=20), nullable=False),
    sa.Column('project_title', sa.String(length=64), nullable=False),
    sa.Column('project_description', sa.String(length=128), nullable=False),
    sa.Column('project_text', sa.Text(), nullable=False),
    sa.Column('project_code', sa.Text(), nullable=False),
    sa.Column('project_trinket_code', sa.String(length=64), nullable=True),
    sa.Column('project_github_code', sa.String(length=64), nullable=True),
    sa.Column('project_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_project_description'), ['project_description'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_project_title'), ['project_title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_title'))
        batch_op.drop_index(batch_op.f('ix_projects_project_description'))

    op.drop_table('projects')
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_blog_title'))

    op.drop_table('blog_post')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
